# Generated by Django 4.0.2 on 2022-02-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201119_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscrm',
            old_name='Status_name',
            new_name='status_name',
        ),
    ]
